[system-requirements]
linux="4.18"

[project]
channels = ["nvidia/label/cuda-12.4.0", "conda-forge", "nodefaults"]
description = "Add a short description here"
name = "ds"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[target.linux-64.dependencies]
python = "3.11.*"
cuda = { channel = "nvidia/label/cuda-12.4.0" }
pandas = "*"
jupyterlab = "*"
pip = "*"
seaborn = "*"
matplotlib = "*"

[target.linux-64.pypi-dependencies]
napari = { version = "*", extras = ["all"] }
ipykernel = "*"
torch = { url = "https://download.pytorch.org/whl/cu124/torch-2.4.0%2Bcu124-cp311-cp311-linux_x86_64.whl#sha256=81397ff1c84a3f2c666d2627144ecac268665325726267e092a80113385ad3e8" }
torchvision = { url = "https://download.pytorch.org/whl/cu124/torchvision-0.19.0%2Bcu124-cp311-cp311-linux_x86_64.whl#sha256=3a877d3eb44f0e89e3442d5242e7e49a9755e709eee327b4629af0078a479023" }
